#[cfg(feature = "oauth")]
pub(super) mod client;
#[cfg(feature = "oauth")]
pub(super) mod data;
#[cfg(feature = "oauth")]
pub(super) mod error;
#[cfg(feature = "oauth")]
pub(crate) mod idp;
#[cfg(feature = "oauth")]
pub(super) mod result;
#[cfg(feature = "oauth")]
pub(super) mod session;
#[cfg(feature = "oauth")]
pub(super) mod token;
