name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build raw
      run: cargo build --features raw --verbose
    - name: Build verify
      run: cargo build --features verify --verbose
    - name: Build raw,verify
      run: cargo build --features verify --verbose
